### ISSUE TITLE
[Bug] add rsync's iconv parameter for single backup lines [sf#27]

### ISSUE THREAD

**Issue by bebehei** [rsnapshot/sourceforge-issues#39]
**Reported by *anonymous on 2010-12-23 19:51 UTC**
My rsnapshot backupserver has UTF8 and i have to backup machines with UTF8 and ISO encodings.
So it would be nice if one can define rsync's iconv parameter for the needed backup lines in the config
like its possible with the exclude parameter.

For testing i added "--iconv=UTF-8,ISO-8859-15" to rsync_long_args. But this fails if the rsync version is to
old on some machines (pre 3.0.x) or there are machines that use already UTF8

**Comment by bebehei** [comment]
**Commented by rvdb on 2011-02-27 13:13 UTC**
I very much second this request. I need to backup different systems which use different encodings. So using rsync_long_args will not work.

**Comment by bebehei** [comment]
**Commented by nobody on 2011-06-21 03:46 UTC**
BCxP9e  &lt;a href="http://ozwixqrkuomk.com/"&gt;ozwixqrkuomk&lt;/a&gt;, [url=http://zxqodiukaaei.com/\]zxqodiukaaei\[/url\], [link=http://qqweisrucwpv.com/\]qqweisrucwpv\[/link\], http://vievupzfxwhw.com/

**Comment by bebehei** [comment]
Closed, either use 2 backup-config-files or use `+rsync_long_args='--iconv...'`

**Comment by yamadzaki** [comment]
How to make it working? Adding `+rsync_long_args='--iconv=UTF-8,UTF-8-MAC'` to rsnapshot.conf and get "Syntax error in extra opts" from rsnapshot.
How to use 2 backup-config-files? 
rsnapshot 1.4.2, Arch.

**Comment by bebehei** [comment]
@yamadzaki you have to use +rsync_long_args after your backup destination:

```
backup  root@server:/       root@server  +rsync_long_args='--iconv=UTF-8,UTF-8-MAC'
```

and of course separated properly with tabs.

**Comment by yamadzaki** [comment]
Thanks for reply  @bebehei , but...

```
[root@localhost ~]# cat /etc/rsnapshot.conf
...
backup  mac@client:/Users/mac/Documents/vagrant/    client/ +rsync_long_args='--iconv=UTF-8,UTF-8-MAC'
...
[root@localhost ~]# rsnapshot alpha
----------------------------------------------------------------------------
rsnapshot encountered an error! The program was invoked with these options:
/usr/bin/rsnapshot alpha
----------------------------------------------------------------------------
ERROR: /etc/rsnapshot.conf on line 253:
ERROR: backup mac@client:/Users/mac/Documents/vagrant/ client/ \
         +rsync_long_args='--iconv=UTF-8,UTF-8-MAC' - Syntax error on \
         line 253 in extra opts: \
         +rsync_long_args='--iconv=UTF-8,UTF-8-MAC'
ERROR: ---------------------------------------------------------------------
ERROR: Errors were found in /etc/rsnapshot.conf,
ERROR: rsnapshot can not continue. If you think an entry looks right, make
ERROR: sure you don't have spaces where only tabs should be.
```

Tabs between backup, source, destination and args. It is Copy-Paste above.
Need assistance.

**Comment by bebehei** [comment]
Are you sure, you have tabs in the correct positions? Here is the scheme:

```
backupTABroot@server:/TABroot@serverTAB+rsync_long_args='--iconv=UTF-8,UTF-8-MAC'
```

**Comment by yamadzaki** [comment]
Check it again now. I'm sure, problem not with tabs.

Replace --iconv... with other argument without comma. It work ok:
`backup mac@client:/Users/mac/Documents/vagrant/    client/ +rsync_long_args='--rsync-path=/opt/local/bin/rsync'`

My vim show points when it tabs and it show points where it needed:
`backup··mac@client:/Users/mac/Documents/vagrant/····client/·+rsync_long_args='--iconv=UTF-8,UTF-8-MAC'`

Sorry, I'm sure tabs in right place.
