### ISSUE TITLE
laep partitions

### ISSUE THREAD

**Issue by bebehei** [rsnapshot/sourceforge-issues#53]
**Reported by e_z_ on 2007-06-28 10:58 UTC**
We have - for security reasons - 3 partitions. One for the daily, one for the weekly and one for the monthly backups. All are mounted raid-arrays.
It isn't that difficult to create 3 different conf - files and assign them to rsnapshot. Unfortunately the cron has to invoke the same routine towards the end of the months for all partitions separately. Rsnapshot is unable to move the last daily e.g. to the next weekly and so on this way.
Does anybody know, how this showstopper can be managed ?

Thanks E.Z.

**Comment by DrHyde** [comment]
It can't be fixed. Hard links don't work across multiple volumes, so moving daily.oldest on one volume to weekly.first on another will always break the links .
